PSE-10014: update cr connection response
PacketFabric/terraform-provider-packetfabric pull request #194
Opened 2022-10-26 17:29 UTC by Favouroked

## Jira Ticket
https://packetfabric.atlassian.net/browse/PSE-10014
https://packetfabric.atlassian.net/browse/PSE-9631

## Cross-reference PRs

https://github.com/PacketFabric/ava/pull/2192
https://github.com/PacketFabric/ava/pull/2215

## Description
Update cloud router connection response. Add `cloud_router_name`, `cloud_router_asn`, `bgp_state_list`. `bgp_state` field is deprecated.

2022-10-26 22:50 UTC, rjouhann commented
The failed Test is expected as the change did not go through production yet.

2022-10-27 08:36 UTC, medzin requested changes

2022-10-27 08:36 UTC, medzin commented on internal/provider/datasource_cloud_conn.go
> +func flattenBgpStateList(bgp_state_list *[]packetfabric.BgpStateObj) []interface{} {
The convention in Go is to use `mixedCaps` for everything, not `snake_case`. Please correct the name.

2022-10-27 08:36 UTC, medzin commented on internal/provider/datasource_cloud_conn.go
> +		for i, bgp_state_obj := range *bgp_state_list {
`mixedCaps` as well.

2022-10-27 08:36 UTC, medzin commented on internal/packetfabric/cloud_router_connection.go
> +type BgpStateObj struct {
Please use `gofmt` for code formatting. All popular editors support it, and it is part of standard Go tooling.

2022-10-28 19:51 UTC, rjouhann commented
Not doing this anymore, see more details on the PSE-10053

2022-10-31 18:40 UTC, rjouhann commented
@medzin I fixed the lint errors. The Test/Test is failing and I can't figure out why. Could you help?

2022-10-31 19:05 UTC, medzin commented
`Test_ReadCloudRouterConnection` fails, but I cannot see why. I need some time to debug it locally.

2022-10-31 19:27 UTC, medzin commented on internal/packetfabric/cloud_router_connection_test.go
> +		"account_uuid": "%s",
The byte slice returned by this function is not processed further by any `fmt` functions. The final value in this place will be literally `%s`.

2022-10-31 19:41 UTC, medzin approved these changes

2022-11-01 03:31 UTC, merged