Fix runtime error.
PacketFabric/terraform-provider-packetfabric pull request #226
Opened 2022-10-31 16:19 UTC by pontovinte

Signed-off-by: Yrineu Rodrigues <yrineu@pontovinte.com>

2022-10-31 16:52 UTC, rjouhann commented
1. the problem keeps happening for `packetfabric_point_to_point` resource (see comment https://github.com/PacketFabric/terraform-provider-packetfabric/issues/225#issuecomment-1296395055)
2. I tried the fix for `packetfabric_backbone_virtual_circuit` and the plugin doesn't crash anymore, however, when creating all the 15 VCs, they all get created correctly but in Terraform, it doesn't seem all of them as completed and the execution never ends ...

When checking the API with one of the VC showing `"packetfabric_backbone_virtual_circuit.vc1 Still creating... [15m0s elapsed]"`, the status shows Complete:

**GET {{url}}/v2.1/services/PF-BC-MIA-LAS-1750321-PF/status**
```
{
    "circuit_id": "PF-BC-MIA-LAS-1750321-PF",
    "status": {
        "object": {
            "state": "Active",
            "deleted": false
        },
        "current": {
            "state": "ACTIVE",
            "description": "active",
            "warning": false
        },
        "last_workflow": {
            "name": "vc/workflow/provision/master",
            "root": "114d622f-425a-4995-822e-72d9427a2ec0",
            "current": "eccb159a-4937-4ac8-8329-8e2419f68611",
            "state": "COMPLETE",
            "current_state": "COMPLETE",
            "prev_state": "NOTIFY_RESELLER_PROVISION_WORKFLOW",
            "is_final": true,
            "progress": {
                "position": 10,
                "steps": 10
            },
            "states": [
                {
                    "state": "WORKFLOW_OBJECT_XREF",
                    "description": "Initialize operation"
                },
                {
                    "state": "CREATE_INTERFACES",
                    "description": "Create interfaces"
                },
                {
                    "state": "CREATE_INTERFACES_CLEANUP",
                    "description": "Cleanup"
                },
                {
                    "state": "ACTIVATE",
                    "description": "Activate VC"
                },
                {
                    "state": "UPDATE_VC_REQUEST_STATUS",
                    "description": "Update VC request"
                },
                {
                    "state": "SET_INITIAL_LINK_STATUS",
                    "description": "Set initial Layer 3 Link status"
                },
                {
                    "state": "NOW",
                    "description": "Workflow step: _now"
                },
                {
                    "state": "BILLING_ADD",
                    "description": "Perform billing operations"
                },
                {
                    "state": "NOTIFY_RESELLER_PROVISION_WORKFLOW",
                    "description": "Send reseller notification"
                },
                {
                    "state": "COMPLETE",
                    "description": "Complete"
                }
            ]
        }
    }
}
```

TF Logs:
```
packetfabric_backbone_virtual_circuit.vc8: Creating...
packetfabric_backbone_virtual_circuit.vc13: Creating...
packetfabric_backbone_virtual_circuit.vc3: Creating...
packetfabric_backbone_virtual_circuit.vc9: Creating...
packetfabric_backbone_virtual_circuit.vc14: Creating...
packetfabric_backbone_virtual_circuit.vc10: Creating...
packetfabric_backbone_virtual_circuit.vc4: Creating...
packetfabric_backbone_virtual_circuit.vc7: Creating...
packetfabric_backbone_virtual_circuit.vc6: Creating...
packetfabric_backbone_virtual_circuit.vc15: Creating...
packetfabric_backbone_virtual_circuit.vc7: Still creating... [10s elapsed]
packetfabric_backbone_virtual_circuit.vc8: Still creating... [10s elapsed]
packetfabric_backbone_virtual_circuit.vc13: Still creating... [10s elapsed]
packetfabric_backbone_virtual_circuit.vc9: Still creating... [10s elapsed]
packetfabric_backbone_virtual_circuit.vc10: Still creating... [10s elapsed]
packetfabric_backbone_virtual_circuit.vc15: Still creating... [10s elapsed]
packetfabric_backbone_virtual_circuit.vc14: Still creating... [10s elapsed]
packetfabric_backbone_virtual_circuit.vc3: Still creating... [10s elapsed]
packetfabric_backbone_virtual_circuit.vc4: Still creating... [10s elapsed]
packetfabric_backbone_virtual_circuit.vc6: Still creating... [10s elapsed]
packetfabric_backbone_virtual_circuit.vc12: Creating...
packetfabric_backbone_virtual_circuit.vc1: Creating...
packetfabric_backbone_virtual_circuit.vc11: Creating...
packetfabric_backbone_virtual_circuit.vc10: Still creating... [20s elapsed]
packetfabric_backbone_virtual_circuit.vc7: Still creating... [20s elapsed]
packetfabric_backbone_virtual_circuit.vc8: Still creating... [20s elapsed]
packetfabric_backbone_virtual_circuit.vc13: Still creating... [20s elapsed]
packetfabric_backbone_virtual_circuit.vc9: Still creating... [20s elapsed]
packetfabric_backbone_virtual_circuit.vc14: Still creating... [20s elapsed]
packetfabric_backbone_virtual_circuit.vc15: Still creating... [20s elapsed]
packetfabric_backbone_virtual_circuit.vc12: Still creating... [10s elapsed]
packetfabric_backbone_virtual_circuit.vc10: Creation complete after 22s [id=PF-BC-NYC-LAX-1750294-PF]
packetfabric_backbone_virtual_circuit.vc5: Creating...
packetfabric_backbone_virtual_circuit.vc8: Creation complete after 22s [id=PF-BC-MIA-LAX-1750295-PF]
packetfabric_backbone_virtual_circuit.vc2: Creating...
packetfabric_backbone_virtual_circuit.vc13: Creation complete after 22s [id=PF-BC-LAX-DAL-1750293-PF]
packetfabric_backbone_virtual_circuit.vc1: Still creating... [10s elapsed]
packetfabric_backbone_virtual_circuit.vc11: Still creating... [10s elapsed]
packetfabric_backbone_virtual_circuit.vc7: Creation complete after 23s [id=PF-BC-MIA-NYC-1750301-PF]
packetfabric_backbone_virtual_circuit.vc14: Creation complete after 23s [id=PF-BC-LAX-LAS-1750299-PF]
packetfabric_backbone_virtual_circuit.vc9: Creation complete after 23s [id=PF-BC-MIA-DAL-1750302-PF]
packetfabric_backbone_virtual_circuit.vc15: Creation complete after 23s [id=PF-BC-DAL-LAS-1750296-PF]
packetfabric_backbone_virtual_circuit.vc12: Still creating... [20s elapsed]
packetfabric_backbone_virtual_circuit.vc5: Still creating... [10s elapsed]
packetfabric_backbone_virtual_circuit.vc2: Still creating... [10s elapsed]
packetfabric_backbone_virtual_circuit.vc1: Still creating... [20s elapsed]
packetfabric_backbone_virtual_circuit.vc11: Still creating... [20s elapsed]
packetfabric_backbone_virtual_circuit.vc12: Still creating... [30s elapsed]
packetfabric_backbone_virtual_circuit.vc1: Still creating... [30s elapsed]
packetfabric_backbone_virtual_circuit.vc11: Still creating... [30s elapsed]
packetfabric_backbone_virtual_circuit.vc12: Still creating... [40s elapsed]
packetfabric_backbone_virtual_circuit.vc1: Still creating... [40s elapsed]
packetfabric_backbone_virtual_circuit.vc11: Still creating... [40s elapsed]
packetfabric_backbone_virtual_circuit.vc12: Still creating... [50s elapsed]
packetfabric_backbone_virtual_circuit.vc1: Still creating... [50s elapsed]
packetfabric_backbone_virtual_circuit.vc11: Still creating... [50s elapsed]
packetfabric_backbone_virtual_circuit.vc12: Still creating... [1m0s elapsed]
packetfabric_backbone_virtual_circuit.vc1: Still creating... [1m0s elapsed]
packetfabric_backbone_virtual_circuit.vc11: Still creating... [1m0s elapsed]
packetfabric_backbone_virtual_circuit.vc12: Still creating... [1m10s elapsed]
packetfabric_backbone_virtual_circuit.vc11: Still creating... [1m10s elapsed]
packetfabric_backbone_virtual_circuit.vc1: Still creating... [1m10s elapsed]
packetfabric_backbone_virtual_circuit.vc12: Still creating... [1m20s elapsed]
packetfabric_backbone_virtual_circuit.vc1: Still creating... [1m20s elapsed]
packetfabric_backbone_virtual_circuit.vc11: Still creating... [1m20s elapsed]
packetfabric_backbone_virtual_circuit.vc12: Still creating... [1m30s elapsed]
packetfabric_backbone_virtual_circuit.vc11: Still creating... [1m30s elapsed]
packetfabric_backbone_virtual_circuit.vc1: Still creating... [1m30s elapsed]
packetfabric_backbone_v [...]

2022-10-31 16:52 UTC, rjouhann requested changes
1. the problem keeps happening for `packetfabric_point_to_point` resource (see comment https://github.com/PacketFabric/terraform-provider-packetfabric/issues/225#issuecomment-1296395055)
2. I tried the fix for `packetfabric_backbone_virtual_circuit` and the plugin doesn't crash anymore, however, when creating all the 15 VCs, they all get created correctly but in Terraform, it doesn't seem all of them as completed and the execution never ends ...

When checking the API with one of the VC showing `"packetfabric_backbone_virtual_circuit.vc1 Still creating... [15m0s elapsed]"`, the status shows Complete:

**GET {{url}}/v2.1/services/PF-BC-MIA-LAS-1750321-PF/status**
```
{
    "circuit_id": "PF-BC-MIA-LAS-1750321-PF",
    "status": {
        "object": {
            "state": "Active",
            "deleted": false
        },
        "current": {
            "state": "ACTIVE",
            "description": "active",
            "warning": false
        },
        "last_workflow": {
            "name": "vc/workflow/provision/master",
            "root": "114d622f-425a-4995-822e-72d9427a2ec0",
            "current": "eccb159a-4937-4ac8-8329-8e2419f68611",
            "state": "COMPLETE",
            "current_state": "COMPLETE",
            "prev_state": "NOTIFY_RESELLER_PROVISION_WORKFLOW",
            "is_final": true,
            "progress": {
                "position": 10,
                "steps": 10
            },
            "states": [
                {
                    "state": "WORKFLOW_OBJECT_XREF",
                    "description": "Initialize operation"
                },
                {
                    "state": "CREATE_INTERFACES",
                    "description": "Create interfaces"
                },
                {
                    "state": "CREATE_INTERFACES_CLEANUP",
                    "description": "Cleanup"
                },
                {
                    "state": "ACTIVATE",
                    "description": "Activate VC"
                },
                {
                    "state": "UPDATE_VC_REQUEST_STATUS",
                    "description": "Update VC request"
                },
                {
                    "state": "SET_INITIAL_LINK_STATUS",
                    "description": "Set initial Layer 3 Link status"
                },
                {
                    "state": "NOW",
                    "description": "Workflow step: _now"
                },
                {
                    "state": "BILLING_ADD",
                    "description": "Perform billing operations"
                },
                {
                    "state": "NOTIFY_RESELLER_PROVISION_WORKFLOW",
                    "description": "Send reseller notification"
                },
                {
                    "state": "COMPLETE",
                    "description": "Complete"
                }
            ]
        }
    }
}
```

TF Logs:
```
packetfabric_backbone_virtual_circuit.vc8: Creating...
packetfabric_backbone_virtual_circuit.vc13: Creating...
packetfabric_backbone_virtual_circuit.vc3: Creating...
packetfabric_backbone_virtual_circuit.vc9: Creating...
packetfabric_backbone_virtual_circuit.vc14: Creating...
packetfabric_backbone_virtual_circuit.vc10: Creating...
packetfabric_backbone_virtual_circuit.vc4: Creating...
packetfabric_backbone_virtual_circuit.vc7: Creating...
packetfabric_backbone_virtual_circuit.vc6: Creating...
packetfabric_backbone_virtual_circuit.vc15: Creating...
packetfabric_backbone_virtual_circuit.vc7: Still creating... [10s elapsed]
packetfabric_backbone_virtual_circuit.vc8: Still creating... [10s elapsed]
packetfabric_backbone_virtual_circuit.vc13: Still creating... [10s elapsed]
packetfabric_backbone_virtual_circuit.vc9: Still creating... [10s elapsed]
packetfabric_backbone_virtual_circuit.vc10: Still creating... [10s elapsed]
packetfabric_backbone_virtual_circuit.vc15: Still creating... [10s elapsed]
packetfabric_backbone_virtual_circuit.vc14: Still creating... [10s elapsed]
packetfabric_backbone_virtual_circuit.vc3: Still creating... [10s elapsed]
packetfabric_backbone_virtual_circuit.vc4: Still creating... [10s elapsed]
packetfabric_backbone_virtual_circuit.vc6: Still creating... [10s elapsed]
packetfabric_backbone_virtual_circuit.vc12: Creating...
packetfabric_backbone_virtual_circuit.vc1: Creating...
packetfabric_backbone_virtual_circuit.vc11: Creating...
packetfabric_backbone_virtual_circuit.vc10: Still creating... [20s elapsed]
packetfabric_backbone_virtual_circuit.vc7: Still creating... [20s elapsed]
packetfabric_backbone_virtual_circuit.vc8: Still creating... [20s elapsed]
packetfabric_backbone_virtual_circuit.vc13: Still creating... [20s elapsed]
packetfabric_backbone_virtual_circuit.vc9: Still creating... [20s elapsed]
packetfabric_backbone_virtual_circuit.vc14: Still creating... [20s elapsed]
packetfabric_backbone_virtual_circuit.vc15: Still creating... [20s elapsed]
packetfabric_backbone_virtual_circuit.vc12: Still creating... [10s elapsed]
packetfabric_backbone_virtual_circuit.vc10: Creation complete after 22s [id=PF-BC-NYC-LAX-1750294-PF]
packetfabric_backbone_virtual_circuit.vc5: Creating...
packetfabric_backbone_virtual_circuit.vc8: Creation complete after 22s [id=PF-BC-MIA-LAX-1750295-PF]
packetfabric_backbone_virtual_circuit.vc2: Creating...
packetfabric_backbone_virtual_circuit.vc13: Creation complete after 22s [id=PF-BC-LAX-DAL-1750293-PF]
packetfabric_backbone_virtual_circuit.vc1: Still creating... [10s elapsed]
packetfabric_backbone_virtual_circuit.vc11: Still creating... [10s elapsed]
packetfabric_backbone_virtual_circuit.vc7: Creation complete after 23s [id=PF-BC-MIA-NYC-1750301-PF]
packetfabric_backbone_virtual_circuit.vc14: Creation complete after 23s [id=PF-BC-LAX-LAS-1750299-PF]
packetfabric_backbone_virtual_circuit.vc9: Creation complete after 23s [id=PF-BC-MIA-DAL-1750302-PF]
packetfabric_backbone_virtual_circuit.vc15: Creation complete after 23s [id=PF-BC-DAL-LAS-1750296-PF]
packetfabric_backbone_virtual_circuit.vc12: Still creating... [20s elapsed]
packetfabric_backbone_virtual_circuit.vc5: Still creating... [10s elapsed]
packetfabric_backbone_virtual_circuit.vc2: Still creating... [10s elapsed]
packetfabric_backbone_virtual_circuit.vc1: Still creating... [20s elapsed]
packetfabric_backbone_virtual_circuit.vc11: Still creating... [20s elapsed]
packetfabric_backbone_virtual_circuit.vc12: Still creating... [30s elapsed]
packetfabric_backbone_virtual_circuit.vc1: Still creating... [30s elapsed]
packetfabric_backbone_virtual_circuit.vc11: Still creating... [30s elapsed]
packetfabric_backbone_virtual_circuit.vc12: Still creating... [40s elapsed]
packetfabric_backbone_virtual_circuit.vc1: Still creating... [40s elapsed]
packetfabric_backbone_virtual_circuit.vc11: Still creating... [40s elapsed]
packetfabric_backbone_virtual_circuit.vc12: Still creating... [50s elapsed]
packetfabric_backbone_virtual_circuit.vc1: Still creating... [50s elapsed]
packetfabric_backbone_virtual_circuit.vc11: Still creating... [50s elapsed]
packetfabric_backbone_virtual_circuit.vc12: Still creating... [1m0s elapsed]
packetfabric_backbone_virtual_circuit.vc1: Still creating... [1m0s elapsed]
packetfabric_backbone_virtual_circuit.vc11: Still creating... [1m0s elapsed]
packetfabric_backbone_virtual_circuit.vc12: Still creating... [1m10s elapsed]
packetfabric_backbone_virtual_circuit.vc11: Still creating... [1m10s elapsed]
packetfabric_backbone_virtual_circuit.vc1: Still creating... [1m10s elapsed]
packetfabric_backbone_virtual_circuit.vc12: Still creating... [1m20s elapsed]
packetfabric_backbone_virtual_circuit.vc1: Still creating... [1m20s elapsed]
packetfabric_backbone_virtual_circuit.vc11: Still creating... [1m20s elapsed]
packetfabric_backbone_virtual_circuit.vc12: Still creating... [1m30s elapsed]
packetfabric_backbone_virtual_circuit.vc11: Still creating... [1m30s elapsed]
packetfabric_backbone_virtual_circuit.vc1: Still creating... [1m30s elapsed]
packetfabric_backbone_v [...]

2022-10-31 17:54 UTC, rjouhann requested changes
I tried the new fix and it still happening with 3 of the VCs and vc2, vc3, vc4, vc6 never get created.

```
packetfabric_backbone_virtual_circuit.vc14: Creating...
packetfabric_backbone_virtual_circuit.vc6: Creating...
packetfabric_backbone_virtual_circuit.vc5: Creating...
packetfabric_backbone_virtual_circuit.vc3: Creating...
packetfabric_backbone_virtual_circuit.vc4: Creating...
packetfabric_backbone_virtual_circuit.vc9: Creating...
packetfabric_backbone_virtual_circuit.vc8: Creating...
packetfabric_backbone_virtual_circuit.vc13: Creating...
packetfabric_backbone_virtual_circuit.vc11: Creating...
packetfabric_backbone_virtual_circuit.vc2: Creating...
packetfabric_backbone_virtual_circuit.vc14: Still creating... [10s elapsed]
packetfabric_backbone_virtual_circuit.vc6: Still creating... [10s elapsed]
packetfabric_backbone_virtual_circuit.vc5: Still creating... [10s elapsed]
packetfabric_backbone_virtual_circuit.vc3: Still creating... [10s elapsed]
packetfabric_backbone_virtual_circuit.vc4: Still creating... [10s elapsed]
packetfabric_backbone_virtual_circuit.vc9: Still creating... [10s elapsed]
packetfabric_backbone_virtual_circuit.vc8: Still creating... [10s elapsed]
packetfabric_backbone_virtual_circuit.vc13: Still creating... [10s elapsed]
packetfabric_backbone_virtual_circuit.vc2: Still creating... [10s elapsed]
packetfabric_backbone_virtual_circuit.vc11: Still creating... [10s elapsed]
packetfabric_backbone_virtual_circuit.vc7: Creating...
packetfabric_backbone_virtual_circuit.vc12: Creating...
packetfabric_backbone_virtual_circuit.vc15: Creating...
packetfabric_backbone_virtual_circuit.vc1: Creating...
packetfabric_backbone_virtual_circuit.vc10: Creating...
packetfabric_backbone_virtual_circuit.vc14: Still creating... [20s elapsed]
packetfabric_backbone_virtual_circuit.vc9: Still creating... [20s elapsed]
packetfabric_backbone_virtual_circuit.vc8: Still creating... [20s elapsed]
packetfabric_backbone_virtual_circuit.vc11: Still creating... [20s elapsed]
packetfabric_backbone_virtual_circuit.vc13: Still creating... [20s elapsed]
packetfabric_backbone_virtual_circuit.vc7: Still creating... [10s elapsed]
packetfabric_backbone_virtual_circuit.vc12: Still creating... [10s elapsed]
packetfabric_backbone_virtual_circuit.vc11: Creation complete after 22s [id=PF-BC-NYC-DAL-1750342-PF]
packetfabric_backbone_virtual_circuit.vc15: Still creating... [10s elapsed]
packetfabric_backbone_virtual_circuit.vc1: Still creating... [10s elapsed]
packetfabric_backbone_virtual_circuit.vc10: Still creating... [10s elapsed]
packetfabric_backbone_virtual_circuit.vc13: Creation complete after 23s [id=PF-BC-LAX-DAL-1750347-PF]
packetfabric_backbone_virtual_circuit.vc14: Still creating... [30s elapsed]
packetfabric_backbone_virtual_circuit.vc9: Still creating... [30s elapsed]
packetfabric_backbone_virtual_circuit.vc8: Still creating... [30s elapsed]
packetfabric_backbone_virtual_circuit.vc7: Still creating... [20s elapsed]
packetfabric_backbone_virtual_circuit.vc12: Still creating... [20s elapsed]
packetfabric_backbone_virtual_circuit.vc15: Still creating... [20s elapsed]
packetfabric_backbone_virtual_circuit.vc1: Still creating... [20s elapsed]
packetfabric_backbone_virtual_circuit.vc7: Creation complete after 21s [id=PF-BC-MIA-NYC-1750361-PF]
packetfabric_backbone_virtual_circuit.vc10: Still creating... [20s elapsed]
packetfabric_backbone_virtual_circuit.vc12: Creation complete after 22s [id=PF-BC-NYC-LAS-1750364-PF]
packetfabric_backbone_virtual_circuit.vc1: Creation complete after 21s [id=PF-BC-MIA-LAS-1750368-PF]
packetfabric_backbone_virtual_circuit.vc15: Creation complete after 21s [id=PF-BC-DAL-LAS-1750367-PF]
packetfabric_backbone_virtual_circuit.vc10: Creation complete after 21s [id=PF-BC-NYC-LAX-1750373-PF]
packetfabric_backbone_virtual_circuit.vc14: Still creating... [40s elapsed]
packetfabric_backbone_virtual_circuit.vc9: Still creating... [40s elapsed]
packetfabric_backbone_virtual_circuit.vc8: Still creating... [40s elapsed]
packetfabric_backbone_virtual_circuit.vc14: Still creating... [50s elapsed]
packetfabric_backbone_virtual_circuit.vc9: Still creating... [50s elapsed]
packetfabric_backbone_virtual_circuit.vc8: Still creating... [50s elapsed]
...

packetfabric_backbone_virtual_circuit.vc14: Still creating... [6m40s elapsed]
packetfabric_backbone_virtual_circuit.vc9: Still creating... [6m40s elapsed]
packetfabric_backbone_virtual_circuit.vc8: Still creating... [6m40s elapsed]
packetfabric_backbone_virtual_circuit.vc8: Still creating... [8m40s elapsed]
packetfabric_backbone_virtual_circuit.vc9: Still creating... [8m40s elapsed]
packetfabric_backbone_virtual_circuit.vc14: Still creating... [8m40s elapsed]
packetfabric_backbone_virtual_circuit.vc14: Still creating... [8m50s elapsed]
packetfabric_backbone_virtual_circuit.vc8: Still creating... [8m50s elapsed]
packetfabric_backbone_virtual_circuit.vc9: Still creating... [8m50s elapsed]
packetfabric_backbone_virtual_circuit.vc8: Still creating... [9m0s elapsed]
packetfabric_backbone_virtual_circuit.vc14: Still creating... [9m0s elapsed]
packetfabric_backbone_virtual_circuit.vc9: Still creating... [9m0s elapsed]
packetfabric_backbone_virtual_circuit.vc14: Still creating... [9m10s elapsed]
packetfabric_backbone_virtual_circuit.vc8: Still creating... [9m10s elapsed]
packetfabric_backbone_virtual_circuit.vc9: Still creating... [9m10s elapsed]
```

- ``packetfabric_backbone_virtual_circuit.vc8``: /v2.1/services/PF-BC-MIA-LAX-1750344-PF/status
```
{
    "circuit_id": "PF-BC-MIA-LAX-1750344-PF",
    "status": {
        "object": {
            "state": "Active",
            "deleted": false
        },
        "current": {
            "state": "ACTIVE",
            "description": "active",
            "warning": false
        },
        "last_workflow": {
            "name": "vc/workflow/provision/master",
            "root": "b99f0f10-f124-4889-8e67-5f98e57b3c5f",
            "current": "7522e235-b863-4a6f-9c46-65c21377523a",
            "state": "COMPLETE",
            "current_state": "COMPLETE",
            "prev_state": "NOTIFY_RESELLER_PROVISION_WORKFLOW",
            "is_final": true,
            "progress": {
                "position": 10,
                "steps": 10
            },
            "states": [
                {
                    "state": "WORKFLOW_OBJECT_XREF",
                    "description": "Initialize operation"
                },
                {
                    "state": "CREATE_INTERFACES",
                    "description": "Create interfaces"
                },
                {
                    "state": "CREATE_INTERFACES_CLEANUP",
                    "description": "Cleanup"
                },
                {
                    "state": "ACTIVATE",
                    "description": "Activate VC"
                },
                {
                    "state": "UPDATE_VC_REQUEST_STATUS",
                    "description": "Update VC request"
                },
                {
                    "state": "SET_INITIAL_LINK_STATUS",
                    "description": "Set initial Layer 3 Link status"
                },
                {
                    "state": "NOW",
                    "description": "Workflow step: _now"
                },
                {
                    "state": "BILLING_ADD",
                    "description": "Perform billing operations"
                },
                {
                    "state": "NOTIFY_RESELLER_PROVISION_WORKFLOW",
                    "description": "Send reseller notification"
                },
                {
                    "state": "COMPLETE",
                    "description": "Complete"
                }
            ]
        }
    }
}
```


- ``packetfabric_backbone_virtual_circuit.vc9``: /v2.1/services/PF-BC-MIA-DAL-1750346-PF/status
```
{
    "circuit_id": "PF-BC-MIA-DAL-1750346-PF",
    "status": {
        "object": {
            "state": "Active",
            "deleted": false
        },
        "cu [...]

2022-11-01 02:50 UTC, pontovinte commented
@rjouhann, for `point_to_point`, the issue isn't related to this server return?
`Cannot create point-to-point bundle as requested ports are not available, or cannot be provisioned as requested`

2022-11-01 03:19 UTC, rjouhann commented
> @rjouhann, for `point_to_point`, the issue isn't related to this server return? `Cannot create point-to-point bundle as requested ports are not available, or cannot be provisioned as requested`

for `point_to_point`, I was trying to create 8 ptp services but only 1 was correct, so it should have successfully created the 1 correct ptp and thrown an error for the 7 incorrect ones.

It actually throws the errors for the 7 ptp but returns the Context error for the one correct ptp. I wondering if we shouldn't apply the same fix we did for the same for backbone virtual circuit https://github.com/PacketFabric/terraform-provider-packetfabric/issues/165

2022-11-01 03:30 UTC, pontovinte commented
@rjouhann, I added some debug logs in order to get a better understand on what's happening with `packetfabric_backbone_virtual_circuit`. Could you please run the test again with `DEBUG` log active?

2022-11-01 03:58 UTC, rjouhann commented
Sent you the debug logs over slack for the VC creation. I can see the context canceled error in the logs on the status endpoint which is strange because when I do it manually using postman at the same time, I don't have a problem and I get the status back.

10 VCs were created successfully out of the 15 I had in my TF config. (edited)

2022-11-01 07:32 UTC, rjouhann approved these changes

2022-11-01 07:32 UTC, merged