#202: Datasource packetfabric_locations_market
PacketFabric/terraform-provider-packetfabric pull request #273
Opened 2022-11-21 21:39 UTC by pontovinte

Signed-off-by: Yrineu Rodrigues <yrineu@pontovinte.com>

## Description

Datasource `packetfabric_locations_market`

Closes #202 

## Cross-reference

## Checklist

- [x] tested locally
- [ ] added/updated acceptance tests
- [ ] add examples (in example folder)
- [ ] generate docs

2022-11-28 17:50 UTC, medzin requested changes

2022-11-28 17:50 UTC, medzin commented on internal/provider/provider.go
> +			"packetfabric_locations_market":              dataSourceLocationsMarkets(),
Should it be named `packetfabric_locations_market` or `packetfabric_locations_markets`?

2022-11-29 09:20 UTC, medzin commented
I added an acceptance test.

2022-11-29 09:20 UTC, medzin submitted a review, later dismissed

2022-11-29 12:17 UTC, elXaptation approved these changes

2022-11-29 17:53 UTC, rjouhann approved these changes

2022-11-29 20:06 UTC, rjouhann approved these changes

2022-11-29 20:11 UTC, caitlinwheeless approved these changes
No additional doc changes from me

2022-11-29 20:14 UTC, rjouhann approved these changes

2022-11-29 20:14 UTC, merged