#207: Datasource packetfabric_port_vlans
PacketFabric/terraform-provider-packetfabric pull request #279
Opened 2022-11-22 17:57 UTC by pontovinte

Signed-off-by: Yrineu Rodrigues <yrineu@pontovinte.com>

## Description

Datasource `packetfabric_port_vlans`
Closes #207 

## Cross-reference

## Checklist

- [x] tested locally
- [ ] added/updated acceptance tests
- [ ] add examples (in example folder)
- [ ] generate docs

2022-11-28 19:10 UTC, medzin commented
Acceptance test added.

2022-11-28 20:47 UTC, elXaptation approved these changes

2022-11-29 07:31 UTC, rjouhann requested changes

2022-11-29 07:31 UTC, rjouhann commented on examples/data-sources/packetfabric_port_vlans/data-source.tf
> +}
@elXaptation should run `terraform fmt` on the examples too.

2022-11-29 17:36 UTC, rjouhann submitted a review, later dismissed

2022-11-29 20:12 UTC, caitlinwheeless submitted a review, later dismissed
No additional doc changes from me

2022-11-29 20:15 UTC, rjouhann approved these changes

2022-11-29 20:16 UTC, merged