#205: Resource packetfabric_port_loa
PacketFabric/terraform-provider-packetfabric pull request #281
Opened 2022-11-22 22:07 UTC by pontovinte

Signed-off-by: Yrineu Rodrigues <yrineu@pontovinte.com>

## Description

Resource packetfabric_port_loa

Closes #205 

## Cross-reference

## Checklist

- [x] tested locally
- [ ] added/updated acceptance tests
- [ ] add examples (in example folder)
- [ ] generate docs

2022-11-28 09:31 UTC, medzin commented
I am working on the acceptance test.

2022-11-28 09:53 UTC, medzin commented
Tests added.

2022-11-28 20:11 UTC, elXaptation submitted a review, later dismissed

2022-11-29 07:32 UTC, rjouhann requested changes

2022-11-29 07:32 UTC, rjouhann commented on examples/resources/packetfabric_port_loa/resource.tf
> +}
@elXaptation should run `terraform fmt` on the examples too.

2022-11-29 22:29 UTC, caitlinwheeless approved these changes
No extra doc changes needed here. There were only 3 descriptions from the schema.

2022-11-29 22:51 UTC, rjouhann approved these changes

2022-11-29 22:55 UTC, caitlinwheeless approved these changes
blurb added, now it's good to go

2022-11-29 23:33 UTC, merged