Testacc/packetfabric cs azure dedicated connection
PacketFabric/terraform-provider-packetfabric pull request #372
Opened 2023-03-06 22:32 UTC by pontovinte

## Description

ACCTest for packetfabric_cs_azure_dedicated_connection

2023-03-07 00:15 UTC, rjouhann commented on internal/testutil/test_hcls.go
> +const CloudServiceAzDedServiceClass = "metro"
Could you update Service Class to `longhaul`?

2023-03-07 08:54 UTC, medzin requested changes

2023-03-08 08:33 UTC, medzin commented
I tested it with production API, and it failed with the following error:

```
Error
Failed
Stacktrace
resource_azure_req_express_dedicated_conn_test.go:17: Step 1/1 error: Check failed: Check 1/7 error: Not found: packetfabric_cs_azure_dedicated_connection.pf_702d8546_f4c8_47b5_9453_392b38e3cdd5 in [root]
```

2023-03-08 16:34 UTC, rjouhann commented
@pontovinte I just found out you can also disable a dedicated cloud the same way you can disable a port using [/v2/ports/{port_circuit_id}/disable](https://docs.packetfabric.com/api/v2/swagger/#/Ports/disable_port).

Only for `dev`, could you disable the dedicated cloud port before deleting it?

2023-03-09 00:14 UTC, rjouhann commented on internal/provider/resource_azure_req_express_dedicated_conn_test.go
> +				Destroy:                   !testutil.IsDevEnv(),
@pontovinte I just found out you can also disable a dedicated cloud the same way you can disable a port using [/v2/ports/{port_circuit_id}/disable](https://docs.packetfabric.com/api/v2/swagger/#/Ports/disable_port).

Only for `dev`, could you disable the dedicated cloud port before deleting it?

2023-03-16 18:35 UTC, pontovinte commented
> > I tested it with production API, and it failed with the following error:
> > ```
> > Error
> > Failed
> > Stacktrace
> > resource_azure_req_express_dedicated_conn_test.go:17: Step 1/1 error: Check failed: Check 1/7 error: Not found: packetfabric_cs_azure_dedicated_connection.pf_702d8546_f4c8_47b5_9453_392b38e3cdd5 in [root]
> > ```
> 
> @pontovinte hard to tell what's wrong here besides the fact it seems the dedicated cloud did not get created. Maybe a problem in the pop selection?

That's hard to tell. But isn't it something related to the Azure account? Some kind of limitation, similar with the one we have with AWS? (just guessing).

2023-03-16 18:54 UTC, rjouhann commented
> That's hard to tell. But isn't it something related to the Azure account? Some kind of limitation, similar with the one we have with AWS? (just guessing).

Let me try to run it manually and do some troubleshooting on our side. I will get back to you!

2023-03-16 23:55 UTC, rjouhann commented
> > That's hard to tell. But isn't it something related to the Azure account? Some kind of limitation, similar with the one we have with AWS? (just guessing).
> 
> Let me try to run it manually and do some troubleshooting on our side. I will get back to you!

This is the error I am getting when I ran the test locally:
```
resource_azure_req_express_dedicated_conn_test.go:17: Step 1/1 error: Check failed: Check 1/7 error: Not found: packetfabric_cs_azure_dedicated_connection.pf_88cb662d_57f9_4f17_bcbc_8acfc506a39e in [root]
```

When I look in the backend logs, I see the following call made:
1. GET `/v2/locations/cloud` with request_params
`{"cloud_provider": "azure", "cloud_connection_type": "dedicated", "nat_capable": "false", "has_cloud_router": "false", "any_type": "false"}` which look good
2. `GET /v2/locations/CHI4/port-availability`

I am not sure what the problem is but here is how the API call to create a dedicated azure connection look like. Know you do not need special Azure access to create one.

```
{
    "pop": "CHI4",
    "account_uuid": "12345",
    "subscription_term": 1,
    "service_class": "longhaul",
    "zone": "A",
    "speed": "10Gbps",
    "description": "demo-romain",
    "encapsulation": "dot1q",
    "port_category": "primary",
}
```

Bear in mind Azure dedicated cloud do not need the same parameters as port (so no media for example), using the GET `/v2/locations/cloud` with the filters should give you the pop and the zone available to create dedicated connection.

Let me know if this is enough info, otherwise if you could add more debug in `Check 1/7`?

Thanks!

2023-03-20 19:43 UTC, rjouhann commented on internal/provider/resource_azure_req_express_dedicated_conn_test.go
> +				ExpectNonEmptyPlan:        true,
As discussed in other PR, let's make sure we don't skip the terraform plan test. so removing `ExpectNonEmptyPlan`. Thanks!

2023-05-16 01:15 UTC, rjouhann commented
Close as duplicate with #425

2023-05-16 01:15 UTC, closed without merging